fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc "Run all unit tests for all SPM modules via xcodebuild"
  lane :unit_test do
    
    modules_dir = File.expand_path("../SwiftHub/Modules", __dir__)

    # Finds out schemes on modules_dir
    test_schemes = Dir.entries(modules_dir).select do |entry|
      path = File.join(modules_dir, entry)
      File.directory?(path) && File.exist?(File.join(path, "Package.swift"))
    end

    project_path = "../SwiftHub.xcodeproj" 
    destination = "'platform=iOS Simulator,name=iPhone 17 Pro'" 

    # Runs tests of each found module
    test_schemes.each do |scheme_name|
      UI.message "================================================="
      UI.message "Running tests to module: #{scheme_name}"
      UI.message "================================================="
      
      command = "xcodebuild test -project #{project_path} -scheme \"#{scheme_name}\" -destination #{destination}"
      
      sh(command)
    end
  end
end