fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc "Execute unit tests"
  lane :unit_test do
    modules_dir = File.expand_path("../SwiftHub/Modules", __dir__)
    results_dir = File.expand_path("../Build", __dir__)
    FileUtils.mkdir_p(results_dir)

    destination = "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0"

    # Finds out modules
    modules = Dir.entries(modules_dir).select do |entry|
      path = File.join(modules_dir, entry)
      File.directory?(path) && File.exist?(File.join(path, "Package.swift"))
    end

    failed_modules = []

    modules.each do |module_name|
      module_path = File.join(modules_dir, module_name)
      result_path = File.join(results_dir, "#{module_name}.xcresult")
      FileUtils.rm_rf(result_path)

      UI.message("Running tests #{module_name}")

      Dir.chdir(module_path) do
        sh("xcodebuild test \
            -scheme #{module_name} \
            -sdk iphonesimulator \
            -destination '#{destination}' \
            -resultBundlePath '#{result_path}' \
            -quiet \
            | xcpretty --test --color",
          raise_on_error: true)
      end
    end
  end
end