fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc 'Runs unit tests'
  lane :unit_test do |options|

    app_scheme   = "SwiftHub"
    test_schemes = ["Core", "Home", "Infrastructure"]
    device_name  = "iPhone 17 Pro"
    output_path  = "fastlane/test_output"
    project_path = "SwiftHub.xcodeproj"

    scan(
      project: project_path,
      scheme: app_scheme,
      destination: "platform=iOS Simulator,name=#{device_name}",
      build_for_testing: true,
      skip_testing: [],
      clean: true
    )

    test_schemes.each do |scheme_name|
      UI.message "----------------------------------------"
      UI.message "Running tests to module: #{scheme_name}"
      UI.message "----------------------------------------"

      scan(
        package_path: "./SwiftHub/Modules/#{scheme_name}",
        scheme: scheme_name,
        destination: "platform=iOS Simulator,name=#{device_name}",
        skip_build: true,
        output_directory: "#{output_path}/#{scheme_name}",
        output_types: "junit,html"
      )
    end
  end
end